test_json_file = "config.json"

# DICTIONARY CONSTANT STRINGS
LABELS = "labels"
FOLDERS = "folders"
INPUT_IMAGE_FOLDER = "input_image_directory"
EXPOSURE_TIME = "exposure_time"
ROOT_FOLDER = "path_to_output_data_root_folder"
CAMERA_SERIAL = "camera_serial_number"
MAX_HEIGHT = "max_display_window_height"
MAX_WIDTH = "max_display_window_width"
EXTENSION = "file_extension"
CAMERA_INFERENCE = "do_camera_inference"
CAMERA_MODE = "camera_mode"
INFERENCE_LABELS = "camera_inference_labels"
CONFIDENCE= "confidence"
DELAY_INTERVAL = "delay_interval_in_frames"
OFFSETX = "OffsetX"
OFFSETY = "OffsetY"
WIDTH = "Width"
HEIGHT = "Height"
